export enum types {
  /* System store */
  GAMES_DATA_UPDATE = <any> 'GAMES_DATA_UPDATE',
  LOCALIZATION_DATA_UPDATE = <any> 'LOCALIZATION_DATA_UPDATE',

  /* Session store */
  SESSION_CHANGE = <any> 'SESSION_CHANGE',

  /* User store */
  USER_DATA_UPDATE = <any> 'USER_DATA_UPDATE',
  TOKEN_UPDATED = <any> 'TOKEN_UPDATED',
  USER_FRIENDS_UPDATE = <any> 'USER_FRIENDS_UPDATE',
  USER_NOTIFICATION_UPDATE = <any> 'USER_NOTIFICATION_UPDATE',
  USER_NOTIFICATION_COUNT_UPDATE = <any> 'USER_NOTIFICATION_COUNT_UPDATE',
  USER_AVATAR_UPDATE = <any> 'USER_AVATAR_UPDATE',
  USER_STATS_UPDATE = <any> 'USER_STATS_UPDATE',

  /* Matches store */
  MATCHES_CURRENT = <any> 'MATCHES_CURRENT',
  MATCHES_FUTURE = <any> 'MATCHES_FUTURE',

  /* Tournament store */
  TOURNAMENT = <any> 'TOURNAMENT',

  /* News store */
  NEWS_DATA_UPDATE = <any> 'NEWS_DATA_UPDATE',
  NEWS_SOCKETS_ADD = <any> 'NEWS_SOCKETS_ADD',
  NEWS_SOCKETS_LIKE = <any> 'NEWS_SOCKETS_LIKE',
  NEWS_SOCKETS_SHARE = <any> 'NEWS_SOCKETS_SHARE',
  NEWS_SOCKETS_VIEW = <any> 'NEWS_SOCKETS_VIEW',
  NEWS_SOCKETS_COMMENT = <any> 'NEWS_SOCKETS_VIEW',

  /* Team store */
  TEAM_DATA_UPDATE = <any> 'TEAM_DATA_UPDATE',
  TEAM_AVATAR_UPDATE = <any> 'TEAM_AVATAR_UPDATE',
}
